### PR TITLE
Fix: Filter Panel Overflow resolves #62

### LINKED ISSUE #62: BUG: Whole app scrolls when filter panel is overflowing
# Description

When the filter panel is getting too big to be contained in the screen (by expanding the filters list) the scroll happens on the app level displacing all elements. 

# Expected behaviour

Only the filter panel should scroll, the rest of the elements should not move

# Reproduction

- Open filter panel
- Open the `filter 0` card
- Add fields by pressing the `+` button until the filter panel overflows
- Scroll

### PR DESCRIPTION
**Pull request by alrapal**
# Description

Filter panel is now scrolling within and does not displace the whole app when overflowing

# Screenshots

Screenshot 2023-01-02 at 12 28 20

resolves #62

### CODE REVIEW

**Comment by RuthgerD** [comment]
Seems like Tag button now overflows to a new row, is that due to the scrollbar taking up space?

**Comment by alrapal** [comment]
> Seems like Tag button now overflows to a new row, is that due to the scrollbar taking up space?

I checked and it does not seem so. It is most likely because the width of the filter panel is currently set by the container's width with #54. 
I did not touch the filter panel in #54 to avoid creating conflicts
since it is currently being reworked =)

**Comment by alrapal** [comment]
How it looks now: 

Screenshot 2023-01-02 at 14 26 52

File: frontend/src/components/Panel.svelte [hunk 1]
```diff
@@ -40,7 +40,7 @@
             <ColorLegend {styles} />
           </div>       
             <div
-              class="mt-auto pointer-events-auto bg-base-200 shadow-md rounded-r-lg" 
+              class="mt-auto pointer-events-auto bg-base-200 shadow-md rounded-r-lg overflow-y-scroll"
```
Comment (ktpa) [inline frontend/src/components/Panel.svelte:43]: While this might enable the scrolling feature, it also causes the previously mentioned bug on Windows to appear where the scroll bar is visible even if no scrolling is needed.

image

**Review by ktpa — CHANGES_REQUESTED** [review]
Might be worth taking a closer look into this issue before approval.

File: frontend/src/components/Panel.svelte (hunk 1 above)
Comment (alrapal) [reply frontend/src/components/Panel.svelte:43]: I agree, but would you mind taking over? I cannot reproduce those bugs since they don't happen on Mac :x, would be very ineffective for me to try to fix something I cannot see

Comment (ktpa) [reply frontend/src/components/Panel.svelte:43]: I'll give it a go.

**Review by alrapal — COMMENTED** [review]
Nice! Unexpected bug

Tried on Mac and it seems to works as intended :D

**Review by ktpa — APPROVED** [review]
